# Generated by Django 4.2.3 on 2023-07-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_order_inscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='inscription',
        ),
    ]
