# Generated by Django 4.2.3 on 2023-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_alter_cake_name_alter_order_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='berries',
            new_name='berry',
        ),
        migrations.AlterField(
            model_name='cake',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
